### ISSUE TITLE
Missing libcom_err in conda 

### ISSUE THREAD

**Issue by MJHarrison-GFDL** [mjharriso/MIDAS#11]
Hi Matt -

It installed OK, but I ran into an issue trying to use:

>>> # horizontal regridding
... ptemp_an_model = ptemp_an.horiz_interp(field='ptemp_an',target=modelGrid)
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/jpk/.conda/envs/analysis/lib/python2.7/site-packages/midas/rectgrid.py", line 2883, in horiz_interp
    import fms_hinterp as hinterp
ImportError: libcom_err.so.3: cannot open shared object file: No such file or directory

-----
Dr. John Krasting, Physical Scientist
NOAA/Geophysical Fluid Dynamics Laboratory
Biogeochemistry, Ecosystems, and Climate Group
201 Forrestal Road, Princeton, NJ 08540
P. (609) 452-5359   |   F. (609) 987-5063
￼

**Comment by MJHarrison-GFDL** [comment]
@jkrasting Is LD_LIBRARY_PATH set ?  (It should not be ) . Also can you send the output from "conda list"

Matt

**Comment by jkrasting** [comment]
LD_LIBRARY_PATH is not set.


conda list
# packages in environment at /home/jpk/.conda/envs/analysis:
#
backports                 1.0                      py27_0    defaults
backports-abc             0.4                       <pip>
backports.shutil-get-terminal-size 1.0.0                     <pip>
backports.ssl-match-hostname 3.4.0.2                   <pip>
backports_abc             0.4                      py27_0    defaults
basemap                   1.0.8.dev0          np110py27_1    ioos
cairo                     1.12.18                       6    defaults
configparser              3.5.0b2                  py27_1    defaults
curl                      7.45.0                        0    defaults
cycler                    0.10.0                   py27_0    defaults
dateutil                  2.4.1                    py27_0    defaults
decorator                 4.0.9                    py27_0    defaults
easydev                   0.5.9                     <pip>
entrypoints               0.2                      py27_1    defaults
eofs                      0.4.1                     <pip>
fontconfig                2.11.1                        5    defaults
freetype                  2.5.5                         1    defaults
functools32               3.2.3.2                  py27_0    defaults
geos                      3.4.2                         4    ioos
get_terminal_size         1.0.0                    py27_0    defaults
hdf5                      1.8.15.1                      2    defaults
ipykernel                 4.3.1                    py27_0    defaults
ipython                   4.2.0                    py27_0    defaults
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                4.1.1                    py27_0    defaults
jinja2                    2.8                      py27_1    defaults
jsonschema                2.5.1                    py27_0    defaults
jupyter                   1.0.0                    py27_3    defaults
jupyter-client            4.2.2                     <pip>
jupyter-console           4.1.1                     <pip>
jupyter-core              4.1.0                     <pip>
jupyter_client            4.2.2                    py27_0    defaults
jupyter_console           4.1.1                    py27_0    defaults
jupyter_core              4.1.0                    py27_0    defaults
lepl                      5.1.3                     <pip>
libgfortran               3.0.0                         1    defaults
libnetcdf                 4.3.3.1                       3    defaults
libpng                    1.6.17                        0    defaults
libsodium                 1.0.10                        0    defaults
libxml2                   2.9.2                         0    defaults
markupsafe                0.23                     py27_2    defaults
matplotlib                1.5.1               np110py27_0    defaults
midas                     1.2                      py27_0    matthewharrison
mistune                   0.7.2                    py27_0    defaults
mkl                       11.3.3                        0    defaults
mpmath                    0.18                      <pip>
myproxyclient             1.3.0                     <pip>
nbconvert                 4.2.0                    py27_0    defaults
nbformat                  4.0.1                    py27_0    defaults
netcdf-fortran            4.4.2                         0    ioos
netcdf4                   1.2.4               np110py27_1    ioos
notebook                  4.2.1                    py27_0    defaults
numexpr                   2.1                       <pip>
numpy                     1.10.4                   py27_2    defaults
openssl                   1.0.2h                        1    defaults
path.py                   8.2.1                    py27_0    defaults
pathlib2                  2.1.0                    py27_0    defaults
pexpect                   4.0.1                    py27_0    defaults
pickleshare               0.7.2                    py27_0    defaults
pip                       8.1.2                    py27_0    defaults
pixman                    0.32.6                        0    defaults
ptyprocess                0.5.1                    py27_0    defaults
pycairo                   1.10.0                   py27_0    defaults
pygments                  2.1.3                    py27_0    defaults
pyparsing                 2.1.4                    py27_0    defaults
pyproj                    1.9.5.1                  py27_0    ioos
pyqt                      4.11.4                   py27_2    defaults
pyshp                     1.2.3                    py27_0    ioos
python                    2.7.11                        0    defaults
python-dateutil           2.5.3                    py27_0    defaults
pytz                      2016.4                   py27_0    defaults
pyudl                     0.1                       <pip>
pyzmq                     15.2.0                   py27_1    defaults
qt                        4.8.7                         2    defaults
qtconsole                 4.2.1                    py27_0    defaults
readline                  6.2                           2    defaults
scipy                     0.17.1              np110py27_0    defaults
seawater                  3.3.2                     <pip>
setuptools                22.0.5                   py27_0    defaults
shapely                   1.2.14                    <pip>
simplegeneric             0.8.1                    py27_1    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.16.9                   py27_0    defaults
six                       1.10.0                   py27_0    defaults
spectrum                  0.5.6                     <pip>
sphinx                    1.2b1                     <pip>
sqlite                    3.13.0                        0    defaults
ssl_match_hostname        3.4.0.2                  py27_1    defaults
terminado                 0.6                      py27_0    defaults
tk                        8.5.18                        0    defaults
tornado                   4.3                      py27_1    defaults
traitlets                 4.2.1                    py27_0    defaults
wheel                     0.29.0                   py27_0    defaults
zeromq                    4.1.4                         0    defaults
zlib                      1.2.8                         3    defaults


-----
Dr. John Krasting, Physical Scientist
NOAA/Geophysical Fluid Dynamics Laboratory
Biogeochemistry, Ecosystems, and Climate Group
201 Forrestal Road, Princeton, NJ 08540
P. (609) 452-5359   |   F. (609) 987-5063

**Comment by MJHarrison-GFDL** [comment]
@adcroft @jkrasting 

1.

Setup a conda environment for MIDAS:

name: MIDAS
dependencies:
- python>=2.7.11
- libgfortran=3.0.0
- basemap=1.0.8.dev0
- numpy=1.10.4
- scipy=0.17.0
- netcdf4=1.2.4
- dateutil=2.4.1
- midas=1.2

2.  Add these channels (in  ~/.condarc)

 - matthewharrison
- ioos
- scitools
- conda-forge

3. Install

conda install midas=1.2

4. Before running

source activate MIDAS

**Comment by MJHarrison-GFDL** [comment]
Conda resolution on dev/testing.


ANACONDA channels:

```
matthewharrison
ioos
scitools
conda-forge
defaults
```

CONDA Environment (contents of .yml)
 
```
name: MIDAS
dependencies:
- python=2.7.11
- libgfortran=3.0.0
- libnetcdf=4.4.0
- netcdf-fortran=4.4.3
- basemap=1.0.8.dev0
- numpy=1.10.4
- scipy=0.17.0
- netcdf4
- dateutil=2.4.1
- jupyter
- midas=1.2
```
INSTALL

`conda install  midas=1.2`

Temporary Fix for NetCDF library

`ln -s <conda-path>/envs/MIDAS/lib/libnetcdf.so <conda-path>/envs/MIDAS/lib/libnetcdf.so.7`

ACTIVATE ENVIRONMENT

`source activate MIDAS`

DO WORK

DEACTIVATE MIDAS environment

`source deactivate`
