### ISSUE TITLE
IndexError: failed to coerce slice entry of type numpy.float64 to integer

### ISSUE THREAD

**Issue by adcroft** [mjharriso/MIDAS#8]
On the PAN cluster the tests run for MOM6-examples have recently started failing inside MIDAS. This does NOT seem to be due to a change in MIDAS so I suspect it is due to changes in the PAN cluster (I tested the previous commit which yielded the same error). Either way, the tests fail  somewhere in MIDAS:

```
Traceback (most recent call last):
  File "create_grids.py", line 101, in <module>
    antarctic_cap=supergrid(xdat=X,ydat=Y,axis_units='degrees',displace_pole=True,r0_pole=r0_pole,lon0_pole=lon0_pole,doughnut=doughnut)                  
  File "/vftmp/Alistair.Adcroft/MIDAS-MOM6_preprocessing/ice_ocean_SIS2/OM4_025/preprocessing/local/lib/python/midas/rectgrid_gen.py", line 112, in __init__
    r,phi = self.displaced_pole(r0_pole,lon0_pole,excluded_fraction=doughnut)
  File "/vftmp/Alistair.Adcroft/MIDAS-MOM6_preprocessing/ice_ocean_SIS2/OM4_025/preprocessing/local/lib/python/midas/rectgrid_gen.py", line 646, in displaced_pole
    return r_out[jmin:,:], phi_out[jmin:,:]        
IndexError: failed to coerce slice entry of type numpy.float64 to integer
```

**Comment by MJHarrison-GFDL** [comment]
This is a bug in numpy 1.11.0b3 which became the default with the recent PAN upgrade

https://github.com/Unidata/netcdf4-python/issues/521

Workaround on the way...

**Comment by MJHarrison-GFDL** [comment]
Commit:
https://github.com/mjharriso/MIDAS/commit/dafff2b06632bb270b2224a8aa950455afe3614a

provides a workaround, but checksums no longer match.  Needs further validation before promoting to master.

**Comment by MJHarrison-GFDL** [comment]
This was a numpy issue. Resolved with anaconda
